const List<String> interviewFields = [
  'Frontend',
  'Backend',
  'Full Stack',
  'Mobile',
  'DevOps',
  'Data/AI',
];

const List<String> interviewLevels = [
  'New Grad',
  'Junior',
  'Mid-level',
  'Senior',
];

const List<String> interviewTypes = [
  'Technical',
  'Behavioral',
  'Mixed',
];

const Map<String, List<String>> programmingLanguagesByField = {
  'Frontend': [
    'TypeScript',
    'JavaScript',
    'React',
    'Next.js',
    'Vue',
    'Nuxt',
    'Angular',
    'Svelte',
    'Dart',
    'Flutter Web',
  ],
  'Backend': [
    'Java',
    'Kotlin',
    'Spring Boot',
    'Go',
    'Node.js',
    'Express',
    'NestJS',
    'Python',
    'Django',
    'FastAPI',
    'Ruby',
    'Ruby on Rails',
    'PHP',
    'Laravel',
    'C#',
    '.NET',
    'Rust',
    'Elixir',
  ],
  'Full Stack': [
    'TypeScript',
    'JavaScript',
    'React',
    'Next.js',
    'Vue',
    'Node.js',
    'NestJS',
    'Python',
    'Django',
    'FastAPI',
    'Java',
    'Spring Boot',
    'Ruby on Rails',
    'PHP',
    'Laravel',
    'C#',
    '.NET',
  ],
  'Mobile': [
    'Swift',
    'SwiftUI',
    'Objective-C',
    'Kotlin',
    'Java',
    'Android',
    'Dart',
    'Flutter',
    'React Native',
    'TypeScript',
    'JavaScript',
    'Jetpack Compose',
  ],
  'DevOps': [
    'Terraform',
    'Docker',
    'Kubernetes',
    'Helm',
    'Bash',
    'Python',
    'Go',
    'Ansible',
    'Jenkins',
    'GitHub Actions',
    'GitLab CI',
    'AWS',
    'GCP',
    'Azure',
    'Linux',
    'Prometheus',
    'Grafana',
  ],
  'Data/AI': [
    'Python',
    'R',
    'SQL',
    'Scala',
    'Julia',
    'PyTorch',
    'TensorFlow',
    'Keras',
    'scikit-learn',
    'Pandas',
    'NumPy',
    'Spark',
    'Hadoop',
    'Airflow',
    'dbt',
    'BigQuery',
    'Snowflake',
  ],
};
